[package]
name = "panduck-font-latin-modern"
version = "1.0.0"
publish = false
authors = ["Aster <192607617@qq.com>"]
description = "Latin Modern: LM Roman, LM Sans Serif, LM Typewriter, LM Dunhill"
repository = "https://github.com/notedge/panduck-theme-collection/tree/main/projects/panduck-font-latin-modern"
readme = "readme.md"
license = "CC0-1.0"
edition = "2021"

[features]
default = []



