[package]
name = "panduck-font-libertinus"
version = "1.0.0"
authors = ["Aster <192607617@qq.com>"]
description = "notedown ast and converter"
repository = "https://github.com/notedge/notedown-rs"
readme = "../../readme.md"
license = "CC0-1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
notedown_ast = { version = "0.14.3", features = ["rsass"] }

[dev-dependencies.panduck-theme-utility]
version = "0.1"
path = "../panduck-theme-utility"

[features]
default = []



